M48
; DRILL file {KiCad 9.0.4} date 2026-01-29T00:13:39+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-29T00:13:39+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X107.28Y-38.9
T2
X107.28Y-34.25
X112.27Y-34.25
M30
